FROM python:3.7.2
ENV PYTHONUNBUFFERED 1
RUN mkdir /report
WORKDIR /report
COPY requirements.txt /report/
RUN pip install -r requirements.txt
COPY . /report/
EXPOSE 8000
#ENTRYPOINT ["uwsgi", "--ini", "report.ini"]
COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
