FROM python:3.7.2
ENV PYTHONUNBUFFERED 1
RUN mkdir /customer
WORKDIR /customer
COPY requirements.txt /customer/
RUN pip install -r requirements.txt
COPY . /customer/
EXPOSE 8000
#ENTRYPOINT ["uwsgi", "--ini", "customer.ini"]
